/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PositionData = IDL.Record({
  'lat' : IDL.Float64,
  'long' : IDL.Float64,
  'altitude' : IDL.Float64,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearAllTrackHistories' : IDL.Func([], [], []),
  'getAllTrackHistories' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(PositionData)))],
      ['query'],
    ),
  'getApiUrl' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTrackHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Vec(PositionData))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'processAircraftData' : IDL.Func([IDL.Vec(IDL.Vec(IDL.Nat8))], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApiUrl' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PositionData = IDL.Record({
    'lat' : IDL.Float64,
    'long' : IDL.Float64,
    'altitude' : IDL.Float64,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearAllTrackHistories' : IDL.Func([], [], []),
    'getAllTrackHistories' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(PositionData)))],
        ['query'],
      ),
    'getApiUrl' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTrackHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(PositionData))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'processAircraftData' : IDL.Func([IDL.Vec(IDL.Vec(IDL.Nat8))], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApiUrl' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };